language: python

services:
  - docker

before_install:
  - docker build -t hbclab/accel-bids -f Dockerfile_exec .

script:
  - docker run --entrypoint /bin/bash hbclab/accel-bids -c ". activate accel; pytest /home/coder/project"

