language: python

services:
  - docker

before_install:
  - docker build -t hbclab/accel-bids -f Dockerfile_exec .
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push hbclab/accel-bids:latest

script:
  - docker run --entrypoint /bin/bash hbclab/accel-bids -c ". activate accel; pytest /home/coder/projects"

