# Base image
FROM ubuntu:18.04

USER root

ENV ND_ENTRYPOINT="/neurodocker/startup.sh"

RUN export ND_ENTRYPOINT="/neurodocker/startup.sh" \
    && mkdir -p /neurodocker \
    && if [ ! -f "$ND_ENTRYPOINT" ]; then \
         echo '#!/usr/bin/env bash' >> "$ND_ENTRYPOINT" \
    &&   echo 'set -e' >> "$ND_ENTRYPOINT" \
    &&   echo 'export USER="${USER:=`whoami`}"' >> "$ND_ENTRYPOINT" \
    &&   echo 'source activate accel' >> "$ND_ENTRYPOINT" \
    &&   echo 'if [ -n "$1" ]; then "$@"; else /usr/bin/env bash; fi' >> "$ND_ENTRYPOINT"; \
    fi \
    && chmod -R 777 /neurodocker && chmod a+s /neurodocker

# Get base utilities
RUN apt-get update \
    && apt-get -y install curl \
    && chmod 777 /opt

# Conda install
ENV PATH="/opt/miniconda-latest/bin:$PATH"

RUN useradd --create-home --shell /bin/bash coder
USER coder

RUN export PATH="/opt/miniconda-latest/bin:$PATH" \
    && conda_installer="/tmp/miniconda.sh" \
    && curl -fsSL --retry 5 -o "$conda_installer" https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && bash "$conda_installer" -b -p /opt/miniconda-latest


RUN mkdir /home/coder/projects
WORKDIR /home/coder/projects

COPY . /home/coder/projects/

RUN conda env create -f environment.yml 

RUN bash -c 'conda init && . /home/coder/.bashrc && . activate accel && pip install -e /home/coder/projects'

USER root
RUN chown -R coder:coder /home/coder/projects

USER coder
# Run as executable
ENTRYPOINT ["/neurodocker/startup.sh", "accel_transform"]
